// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpUjaLjVv4JhPo6JD4soXTxEEwyEqMhVA',
    appId: '1:1059694001217:web:233d0abae478d4a5491ac0',
    messagingSenderId: '1059694001217',
    projectId: 'chat-app-my-43591',
    authDomain: 'chat-app-my-43591.firebaseapp.com',
    storageBucket: 'chat-app-my-43591.appspot.com',
    measurementId: 'G-MZKQW012YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV3MOdGDsgC5RSuYotS8g_b0vhhLC5QFw',
    appId: '1:1059694001217:android:6e9764c1cd0cffd1491ac0',
    messagingSenderId: '1059694001217',
    projectId: 'chat-app-my-43591',
    storageBucket: 'chat-app-my-43591.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjCOmUI_qJKVIO2kcdAJAkn8NKh4CoeJ4',
    appId: '1:1059694001217:ios:6f791ee56d9d84ef491ac0',
    messagingSenderId: '1059694001217',
    projectId: 'chat-app-my-43591',
    storageBucket: 'chat-app-my-43591.appspot.com',
    iosClientId: '1059694001217-b0kqp20r7gp0mdbg2t0tk2l29dj2cune.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjCOmUI_qJKVIO2kcdAJAkn8NKh4CoeJ4',
    appId: '1:1059694001217:ios:6f791ee56d9d84ef491ac0',
    messagingSenderId: '1059694001217',
    projectId: 'chat-app-my-43591',
    storageBucket: 'chat-app-my-43591.appspot.com',
    iosClientId: '1059694001217-b0kqp20r7gp0mdbg2t0tk2l29dj2cune.apps.googleusercontent.com',
    iosBundleId: 'com.example.pizzaAppUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmCSF8rwa_uJLaBRefPF5MXbw-_CkNUxA',
    appId: '1:1059694001217:web:bae4ead9a35ba5b7491ac0',
    messagingSenderId: '1059694001217',
    projectId: 'chat-app-my-43591',
    authDomain: 'chat-app-my-43591.firebaseapp.com',
    storageBucket: 'chat-app-my-43591.appspot.com',
    measurementId: 'G-3ECMNYDKNC',
  );
}
